networks:
  mongoLojas:
    driver: bridge

services:
  mongo-config1:
    image: mongo
    container_name: config1
    networks:
      - mongoLojas
    command: ['mongod', '--configsvr', '--replSet', 'config-server', '--port', '27017']

  mongo-config2:
    image: mongo
    container_name: config2
    networks:
      - mongoLojas
    command: ['mongod', '--configsvr', '--replSet', 'config-server', '--port', '27017']

  mongo-config3:
    image: mongo
    container_name: config3
    networks:
      - mongoLojas
    command: ['mongod', '--configsvr', '--replSet', 'config-server', '--port', '27017']

  mongo-shard1a:
    image: mongo
    container_name: shard1a
    networks:
      - mongoLojas
    command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--port', '27018']

  mongo-shard1b:
    image: mongo
    container_name: shard1b
    networks:
      - mongoLojas
    command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--port', '27018']

  mongo-shard1c:
    image: mongo
    container_name: shard1c
    networks:
      - mongoLojas
    command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--port', '27018']

  config-srv-setup:
    image: mongo
    container_name: config-srv-setup
    volumes:
      - .\scripts:/scripts
    depends_on:
      - mongo-config1
      - mongo-config2
      - mongo-config3
    networks:
      - mongoLojas
    restart: no
    entrypoint: ['bash', './scripts/start-configdb.sh']

  shard1-setup:
    image: mongo
    container_name: shard1-setup
    volumes:
      - .\scripts:/scripts
    depends_on:
      - mongo-shard1a
      - mongo-shard1b
      - mongo-shard1c
    networks:
      - mongoLojas
    restart: no
    entrypoint: ['bash', './scripts/start-shard1.sh']
